site_name: GodotSteam
site_url: https://godotsteam.com
site_description: An open-source and fully functional Steamworks SDK / API module and plug-in for the Godot Game Engine.
site_author: GP Garcia
copyright: Copyright &copy; 2015-2023 GP Garcia | CoaguCo Industries
repo_url: https://github.com/CoaguCo-Industries/GodotSteam
repo_name: GodotSteam
nav:
  - Introduction: 'index.md'
  - How-To's:
    - How-To Godot 2, 3, 4: 'howto/modules.md'
    - How-To GDNative: 'howto/gdnative.md'
    - How-To GDExtension: 'howto/gdextension.md'
    - How-To Server: 'howto/server.md'
  - Classes:
    - Main: 'classes/main.md'
    - App Lists: 'classes/app_lists.md'
    - Apps: 'classes/apps.md'
    - Friends: 'classes/friends.md'
    - Game Search: 'classes/game_search.md'
    - Game Server: 'classes/game_server.md'
    - Game Server Stats: 'classes/game_server_stats.md'
    - HTML Surface: 'classes/html_surface.md'
    - HTTP: 'classes/http.md'
    - Input: 'classes/input.md'
    - Inventory: 'classes/inventory.md'
    - Matchmaking: 'classes/matchmaking.md'
    - Matchmaking Servers: 'classes/matchmaking_servers.md'
    - Music: 'classes/music.md'
    - Music Remote: 'classes/music_remote.md'
    - Networking: 'classes/networking.md'
    - Networking Messages: 'classes/networking_messages.md'
    - Networking Sockets: 'classes/networking_sockets.md'
    - Networking Types: 'classes/networking_types.md'
    - Networking Utils: 'classes/networking_utils.md'
    - Parental Settings: 'classes/parental_settings.md'
    - Parties: 'classes/parties.md'
    - Remote Play: 'classes/remote_play.md'
    - Remote Storage: 'classes/remote_storage.md'
    - Screenshots: 'classes/screenshots.md'
    - UGC: 'classes/ugc.md'
    - User: 'classes/user.md'
    - User Stats: 'classes/user_stats.md'
    - Utilities: 'classes/utils.md'
    - Video: 'classes/video.md'
  - Tutorials:
    - Achievement Icons: 'tutorials/achievement_icons.md'
    - Authentication: 'tutorials/authentication.md'
    - Auto-Matchmaking: 'tutorials/auto_matchmaking.md'
    - Avatars: 'tutorials/avatars.md'
    - C#: 'tutorials/c-sharp.md'
    - Common Issues: 'tutorials/common_issues.md'
    - Exporting and Shipping: 'tutorials/exporting_shipping.md'
    - Friends' Lobbies: 'tutorials/friends_lobbies.md'
    - Initializing Steam: 'tutorials/initializing.md'
    - Leaderboards: 'tutorials/leaderboards.md'
    - Linux Caveats: 'tutorials/linux_caveats.md'
    - Lobbies: 'tutorials/lobbies.md'
    - Mac Caveats: 'tutorials/mac_caveats.md'
    - Mac Exporting: 'tutorials/mac_export.md'
    - P2P Networking: 'tutorials/p2p.md'
    - Remove Steam: 'tutorials/remove_steam.md'
    - Rich Presence: 'tutorials/rich_presence.md'
    - Stats and Achievements: 'tutorials/stats_achievements.md'
    - Workshop: 'tutorials/workshop.md'
  - Games Using GodotSteam: 'games.md'
  - To-Do: 'https://github.com/orgs/CoaguCo-Industries/projects/2'
  - Change-Logs:
    - Godot 4.x: 'changelog/godot4.md'
    - Godot 3.x: 'changelog/godot3.md'
    - Godot 2.x: 'changelog/godot2.md'
    - GDExtension: 'changelog/gdextension.md'
    - GDNative: 'changelog/gdnative.md'
    - Server: 'changelog/server.md'
  - Contributors:
    - Contributor List: 'contributors.md'
    - Contributing Code: 'contribute_rules.md'
    - Donating: 'contribute_donations.md'
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/inverted-logo.png
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CoaguCo-Industries/GodotSteam
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.gamedev.place/@coaguco
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/coaguco
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@godotsteam.com
extra_css:
  - assets/stylesheets/extra.css
