on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string
      godot_version:
        required: true
        type: string
      steamworks_sdk_tag:
        required: true
        type: string
    secrets:
      steamworks_sdk_repo:
        required: true
      steamworks_sdk_repo_token:
        required: true


jobs:
  build-windows:
    runs-on: windows-latest


    name: Windows ${{ matrix.name }}


    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor and Templates (64-bit)
            bits: x86_64
            cache-name: windows64
            editor-name: godot.windows.opt.tools.64.exe
            editor-name-new: godotsteam.${{ inputs.godot_version }}.editor.windows.64.exe
            debug-name: godot.windows.opt.debug.64.exe
            debug-name-new: godotsteam.${{ inputs.godot_version }}.debug.template.windows.64.exe
            release-name: godot.windows.opt.64.exe
            release-name-new: godotsteam.${{ inputs.godot_version }}.template.windows.64.exe
            steam-redist: steam_api64.dll
            steam-redist-bin: win64/
            steam-redist-bits: 64

          - name: Editor and Templates (32-bit)
            bits: x86_32
            cache-name: windows32
            editor-name: godot.windows.opt.tools.32.exe
            editor-name-new: godotsteam.${{ inputs.godot_version }}.editor.windows.32.exe
            debug-name: godot.windows.opt.debug.32.exe
            debug-name-new: godotsteam.${{ inputs.godot_version }}.debug.template.windows.32.exe
            release-name: godot.windows.opt.32.exe
            release-name-new: godotsteam.${{ inputs.godot_version }}.template.windows.32.exe
            steam-redist: steam_api.dll
            steam-redist-bin: ""
            steam-redist-bits: 32


    steps:
      - uses: actions/checkout@v4

      # Download Godot to start
      - name: Download Godot
        uses: ./.github/actions/download-godot
        with:
          version: ${{ inputs.godot_tag }}

      # Preempt the missing bin folder
      - name: Preempt missing Bin Folder
        shell: bash
        run: |
          mkdir ./bin/

      # Download GodotSteam
      - name: Download GodotSteam
        uses: ./.github/actions/download-godotsteam

      # Download Steamworks SDK
      - name: Download Steamworks SDK
        uses: ./.github/actions/download-steamworks
        with:
          path: "steamworks"
          repository: ${{ secrets.steamworks_sdk_repo }}
          token: ${{ secrets.steamworks_sdk_repo_token }}
          ref: ${{ inputs.steamworks_sdk_tag }}

      # Get that cache money
      - name: Setup Build Cache
        uses: ./.github/actions/setup-cache
        with:
          cache-name: ${{ matrix.cache-name }}
          godot-base: inputs.godot_tag
        continue-on-error: true

      # Setup Python and SCONS
      - name: Setup Python and SCONS
        uses: ./.github/actions/setup-dependencies

      # Compiling editor
      - name: ${{ matrix.bits }}-bit Editor Compilation
        uses: ./.github/actions/build-godot
        with:
          sconsflags: bits=${{ matrix.bits }} tools=yes
          platform: windows
          target: release_debug
          binary: ${{ matrix.editor-name }}
          export: ${{ matrix.editor-name-new }}

      - name: Upload ${{ matrix.bits }}-bit Editor
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-editor
          path: ./bin/${{ matrix.editor-name-new }}

      - name: Clear bin
        shell: bash
        run: |
          rm -rf bin

      # Compiling templates
      - name: ${{ matrix.bits }}-bit Debug Template Compilation (target=template_debug)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: bits=${{ matrix.bits }} tools=no
          platform: windows
          target: release_debug
          binary: ${{ matrix.debug-name }}
          export: ${{ matrix.debug-name-new }}

      - name: Upload ${{ matrix.bits }}-bit Debug Template
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-debug-template
          path: ./bin/${{ matrix.debug-name-new }}

      - name: ${{ matrix.bits }}-bit Release Template Compilation (target=template_release)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: bits=${{ matrix.bits }} debug_symbols=no tools=no
          platform: windows
          target: release
          binary: ${{ matrix.release-name }}
          export: ${{ matrix.release-name-new }}

      - name: Upload ${{ matrix.bits }}-bit Release Template
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-release-template
          path: ./bin/${{ matrix.release-name-new }}

      - name: Clear bin
        shell: bash
        run: |
          rm -rf bin

      # Upload the Steam redistributable for packaging
      - name: Upload Windows ${{ matrix.steam-redist-bits}}-bit Steam File
        uses: ./.github/actions/upload-steam-redistributable
        with:
          name: windows${{ matrix.steam-redist-bits }}-steam
          path: ${{ matrix.steam-redist-bin }}
          redist: ${{ matrix.steam-redist }}
