on:
  workflow_call:
    inputs:
      steamworks_sdk_tag:
        required: true
        type: string
      godot_tag:
        required: true
        type: string
      godotsteam_tag:
        required: true
        type: string
      binary_name:
        required: true
        type: string
      build_params:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      export_name:
        required: true
        type: string
    secrets:
      steamworks_sdk_repo:
        required: true
      steamworks_sdk_repo_token:
        required: true


jobs:
  build-linux:
    runs-on: self-hosted
    
    steps:
      # Checkout Godot
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: "godotengine/godot"
          path: "godot"
          ref: ${{ inputs.godot_tag }}
      # Checkout current source of GodotSteam
      - name: Checkout GodotSteam
        uses: actions/checkout@v3
        with:
          repository: "CoaguCo-Industries/GodotSteam"
          path: "godotsteam"
          ref: ${{ inputs.godotsteam_tag }}
      - name: Copy GodotSteam Module
        run: |
          cp -r godotsteam godot/modules/godotsteam
      # Checkout Steamworks SDK
      - name: Checkout Steamworks SDK
        uses: actions/checkout@v3
        with:
          path: "steamworks"
          repository: ${{ secrets.steamworks_sdk_repo }}
          token: ${{ secrets.steamworks_sdk_repo_token }}
          ref: ${{ inputs.steamworks_sdk_tag }}
      - name: Copy Steamworks
        run: |
          mkdir godot/modules/godotsteam/sdk/public
          cp -r steamworks/public godot/modules/godotsteam/sdk
          cp -r steamworks/redistributable_bin godot/modules/godotsteam/sdk
      # Checkout GodotSteam Multiplayer Peer
      - name: Checkout GodotSteam Multiplayer Peer
        uses: actions/checkout@v3
        with:
          path: "godotsteammultiplayer"
      - name: Copy GodotSteam Multiplayer Module
        run: |
          cp -r godotsteammultiplayer godot/modules/godotsteammultiplayer
      # Build it
      - name: Build Linux Binary
        working-directory: "godot"
        run: |
          PATH=/opt/x86_64-godot-linux-gnu_sdk-buildroot/bin:$PATH scons ${{ inputs.build_params }}
          mv bin/${{ inputs.binary_name }} bin/${{ inputs.export_name }}
      - name: Upload Linux Build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: godot/bin/${{ inputs.export_name }}
          retention-days: 1
      - name: Upload Linux Steam File
        uses: actions/upload-artifact@v3
        with:
          name: linux-libsteam-api-so
          path: godot/modules/godotsteam/sdk/redistributable_bin/linux64/libsteam_api.so
          retention-days: 1
